# Generated by Django 5.2.2 on 2025-09-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_alter_address_id_alter_letting_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
