# Generated by Django 5.2.2 on 2025-09-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_alter_address_id_alter_letting_id_alter_profile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oc_lettings_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
