# Generated by Django 5.2.2 on 2025-09-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_alter_profile_user'),
        ('oc_lettings_site', '0004_delete_old_data'),
    ]

    operations = [
    ]
